// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type TodoAddNew struct {
	Text string `json:"text"`
}

type TodoDeleteExisting struct {
	ID string `json:"id"`
}

type TodoUpdateExisting struct {
	ID   string `json:"id"`
	Done bool   `json:"done"`
}
